# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'arm-deployment-connection'
      subscriptionId: 'e7a3f85c-ec63-4b25-be59-a449da46e127'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'NetworkWatcherRG'
      location: 'Central US'
      templateLocation: 'URL of the file'
      csmFileLink: '**\*.json'
      csmParametersFileLink: '**\*.param.json'
      deploymentMode: 'Complete'
      deploymentName: 'vm'

