# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'arm-deployment-connection'
    ScriptPath: 'AzureResourceGroup1/Deploy-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'NetworkWatcherRG' -ResourceGroupLocation 'centralus'
    azurePowerShellVersion: LatestVersion
